import type { MatchSettings, Player } from './types'

export const defaultSettings: MatchSettings = {
  eventName: 'SHINE ON THE COURT',
  courtCount: 4,
  seed: 11,
  singleGuestPerMatch: true,
  targetRoundCount: 8,
}

export const defaultPlayers: Player[] = [
  {
    id: 'guest-ko',
    name: '고성현',
    level: '스페셜',
    ageGroup: '30대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 5,
  },
  {
    id: 'guest-shin',
    name: '신백철',
    level: '스페셜',
    ageGroup: '30대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 5,
  },
  {
    id: 'guest-special',
    name: '스페셜 1',
    level: '스페셜',
    ageGroup: '40대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 4,
  },
  {
    id: 'p-minsu',
    name: '참가자 1',
    level: 'A',
    ageGroup: '30대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-jiyeon',
    name: '참가자 2',
    level: 'A',
    ageGroup: '30대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-taeho',
    name: '참가자 3',
    level: 'B',
    ageGroup: '40대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-soobin',
    name: '참가자 4',
    level: 'B',
    ageGroup: '20대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-hyunwoo',
    name: '참가자 5',
    level: 'B',
    ageGroup: '45대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-nayoung',
    name: '참가자 6',
    level: 'B',
    ageGroup: '40대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-junho',
    name: '참가자 7',
    level: 'C',
    ageGroup: '50대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-eunji',
    name: '참가자 8',
    level: 'C',
    ageGroup: '45대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-doyoon',
    name: '참가자 9',
    level: 'C',
    ageGroup: '30대',
    gender: 'male',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-yuna',
    name: '참가자 10',
    level: 'C',
    ageGroup: '50대',
    gender: 'female',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-chulsoo',
    name: '참가자 11',
    level: 'D',
    ageGroup: '55대이상',
    gender: 'male',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-harin',
    name: '참가자 12',
    level: 'D',
    ageGroup: '20대',
    gender: 'female',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
]
