import type { MatchSettings, Player } from './types'

export const defaultSettings: MatchSettings = {
  eventName: 'SHINE ON THE COURT',
  courtCount: 4,
  seed: 11,
  singleGuestPerMatch: true,
  targetRoundCount: 8,
}

export const defaultPlayers: Player[] = [
  {
    id: 'guest-ko',
    name: '고성현',
    level: '스페셜',
    ageGroup: '30대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 5,
  },
  {
    id: 'guest-shin',
    name: '신백철',
    level: '스페셜',
    ageGroup: '30대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 5,
  },
  {
    id: 'guest-special',
    name: '스페셜 선수',
    level: '스페셜',
    ageGroup: '40대',
    gender: 'none',
    active: true,
    specialRequired: false,
    isGuest: true,
    guestGameLimit: 4,
  },
  {
    id: 'p-minsu',
    name: '김민수',
    level: 'A',
    ageGroup: '30대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-jiyeon',
    name: '이지연',
    level: 'A',
    ageGroup: '30대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-taeho',
    name: '박태호',
    level: 'B',
    ageGroup: '40대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-soobin',
    name: '최수빈',
    level: 'B',
    ageGroup: '20대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-hyunwoo',
    name: '정현우',
    level: 'B',
    ageGroup: '45대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-nayoung',
    name: '강나영',
    level: 'B',
    ageGroup: '40대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-junho',
    name: '오준호',
    level: 'C',
    ageGroup: '50대',
    gender: 'male',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-eunji',
    name: '한은지',
    level: 'C',
    ageGroup: '45대',
    gender: 'female',
    active: true,
    specialRequired: true,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-doyoon',
    name: '윤도윤',
    level: 'C',
    ageGroup: '30대',
    gender: 'male',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-yuna',
    name: '서유나',
    level: 'C',
    ageGroup: '50대',
    gender: 'female',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-chulsoo',
    name: '이철수',
    level: 'D',
    ageGroup: '55대이상',
    gender: 'male',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
  {
    id: 'p-harin',
    name: '문하린',
    level: 'D',
    ageGroup: '20대',
    gender: 'female',
    active: true,
    specialRequired: false,
    isGuest: false,
    guestGameLimit: 0,
  },
]
